### ISSUE TITLE
shary info on anonfile link: list index out of range error

### ISSUE THREAD

**Issue by aaronlyy** [aaronlyy/shary#2]
C:\Users\acan3\Desktop>shary info https://anonfile.com/n1x8h8ranc
Traceback (most recent call last):
  File "shary.py", line 110, in <module>
  File "site-packages\click\core.py", line 764, in __call__
  File "site-packages\click\core.py", line 717, in main
  File "site-packages\click\core.py", line 1137, in invoke
  File "site-packages\click\core.py", line 956, in invoke
  File "site-packages\click\core.py", line 555, in invoke
  File "shary.py", line 81, in info
IndexError: list index out of range
[20228] Failed to execute script shary

**Comment by aaronlyy** [comment]
fixed
